# Generated by Django 4.2.3 on 2023-07-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_options_comment_level_comment_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parenr',
            new_name='parent',
        ),
    ]
